// <auto-generated />
using System;
using DoAnPhanMem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnPhanMem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251211180004_TaoDatabase")]
    partial class TaoDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoAnPhanMem.Models.BAO_CAO_CONG_NO", b =>
                {
                    b.Property<string>("MaBCCN")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal>("NoCuoi")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("NoDau")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("NoPhatSinh")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("MaBCCN");

                    b.HasIndex("MaKH");

                    b.ToTable("BAO_CAO_CONG_NO");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.BAO_CAO_TON", b =>
                {
                    b.Property<string>("MaBCT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("PhatSinh")
                        .HasColumnType("int");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<int>("Thang")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("TonCuoi")
                        .HasColumnType("int");

                    b.Property<int>("TonDau")
                        .HasColumnType("int");

                    b.HasKey("MaBCT");

                    b.HasIndex("MaSach");

                    b.ToTable("BAO_CAO_TON");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.CHI_TIET_HOA_DON", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("DonGiaBan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("NgayLapHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CHI_TIET_HOA_DON");

                    b.HasCheckConstraint("CK_CTHD_SoLuong", "SoLuong > 0");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.CHI_TIET_PHIEU_NHAP", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaPhieu", "MaSach");

                    b.HasIndex("MaSach");

                    b.ToTable("CHI_TIET_PHIEU_NHAP");

                    b.HasCheckConstraint("CK_CTPN_SoLuong", "SoLuongNhap > 0");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.HOA_DON", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("HOA_DON");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.KHACH_HANG", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CongNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKH");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("KHACH_HANG");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.NHAN_VIEN", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNV");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NHAN_VIEN");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.PHIEU_NHAP_SACH", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaNV");

                    b.ToTable("PHIEU_NHAP_SACH");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.PHIEU_THU_TIEN", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayThuTien")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienThu")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("PHIEU_THU_TIEN");

                    b.HasCheckConstraint("CK_PTT_SoTien", "SoTienThu > 0");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.QUY_DINH", b =>
                {
                    b.Property<string>("TenQuyDinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("bit");

                    b.HasKey("TenQuyDinh");

                    b.HasIndex("MaNV");

                    b.ToTable("QUY_DINH");

                    b.HasData(
                        new
                        {
                            TenQuyDinh = "QD1_NhapToiThieu",
                            GiaTri = "150",
                            TrangThai = true
                        },
                        new
                        {
                            TenQuyDinh = "QD1_TonToiDaTruocNhap",
                            GiaTri = "300",
                            TrangThai = true
                        },
                        new
                        {
                            TenQuyDinh = "QD2_NoToiDa",
                            GiaTri = "20000",
                            TrangThai = true
                        },
                        new
                        {
                            TenQuyDinh = "QD2_TonToiThieuSauBan",
                            GiaTri = "20",
                            TrangThai = true
                        },
                        new
                        {
                            TenQuyDinh = "QD4_KiemTraTienThu",
                            GiaTri = "1",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DoAnPhanMem.Models.SACH", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaTL");

                    b.ToTable("SACH");

                    b.HasCheckConstraint("CK_SACH_SoLuongTon_Valid", "SoLuongTon >= 0");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.SACH_TAC_GIA", b =>
                {
                    b.Property<string>("MaSach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaTG")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaSach", "MaTG");

                    b.HasIndex("MaTG");

                    b.ToTable("SACH_TAC_GIA");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.TAC_GIA", b =>
                {
                    b.Property<string>("MaTG")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTG")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTG");

                    b.ToTable("TAC_GIA");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.TAI_KHOAN", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TAI_KHOAN");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.THE_LOAI", b =>
                {
                    b.Property<string>("MaTL")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTL");

                    b.ToTable("THE_LOAI");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.BAO_CAO_CONG_NO", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.KHACH_HANG", "KhachHang")
                        .WithMany("BaoCaoCongNo")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.BAO_CAO_TON", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.SACH", "Sach")
                        .WithMany("BaoCaoTon")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.CHI_TIET_HOA_DON", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.HOA_DON", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnPhanMem.Models.SACH", "Sach")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.CHI_TIET_PHIEU_NHAP", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.PHIEU_NHAP_SACH", "PhieuNhapSach")
                        .WithMany("ChiTietPhieuNhap")
                        .HasForeignKey("MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnPhanMem.Models.SACH", "Sach")
                        .WithMany("ChiTietPhieuNhap")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuNhapSach");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.HOA_DON", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.KHACH_HANG", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnPhanMem.Models.NHAN_VIEN", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.KHACH_HANG", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.TAI_KHOAN", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("DoAnPhanMem.Models.KHACH_HANG", "TenDangNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.NHAN_VIEN", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.TAI_KHOAN", "TaiKhoan")
                        .WithOne("NhanVien")
                        .HasForeignKey("DoAnPhanMem.Models.NHAN_VIEN", "TenDangNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.PHIEU_NHAP_SACH", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.NHAN_VIEN", "NhanVien")
                        .WithMany("PhieuNhapSach")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.PHIEU_THU_TIEN", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.KHACH_HANG", "KhachHang")
                        .WithMany("PhieuThuTien")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnPhanMem.Models.NHAN_VIEN", "NhanVien")
                        .WithMany("PhieuThuTien")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.QUY_DINH", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.NHAN_VIEN", "NhanVien")
                        .WithMany("QuyDinh")
                        .HasForeignKey("MaNV");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.SACH", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.THE_LOAI", "TheLoai")
                        .WithMany("Sach")
                        .HasForeignKey("MaTL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.SACH_TAC_GIA", b =>
                {
                    b.HasOne("DoAnPhanMem.Models.SACH", "Sach")
                        .WithMany("SachTacGia")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnPhanMem.Models.TAC_GIA", "TacGia")
                        .WithMany("SachTacGia")
                        .HasForeignKey("MaTG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.HOA_DON", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.KHACH_HANG", b =>
                {
                    b.Navigation("BaoCaoCongNo");

                    b.Navigation("HoaDon");

                    b.Navigation("PhieuThuTien");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.NHAN_VIEN", b =>
                {
                    b.Navigation("HoaDon");

                    b.Navigation("PhieuNhapSach");

                    b.Navigation("PhieuThuTien");

                    b.Navigation("QuyDinh");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.PHIEU_NHAP_SACH", b =>
                {
                    b.Navigation("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.SACH", b =>
                {
                    b.Navigation("BaoCaoTon");

                    b.Navigation("ChiTietHoaDon");

                    b.Navigation("ChiTietPhieuNhap");

                    b.Navigation("SachTacGia");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.TAC_GIA", b =>
                {
                    b.Navigation("SachTacGia");
                });

            modelBuilder.Entity("DoAnPhanMem.Models.TAI_KHOAN", b =>
                {
                    b.Navigation("KhachHang")
                        .IsRequired();

                    b.Navigation("NhanVien")
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnPhanMem.Models.THE_LOAI", b =>
                {
                    b.Navigation("Sach");
                });
#pragma warning restore 612, 618
        }
    }
}
